# <center>Assignment 2</center>

## 1. Define a function to analyze a numpy array
 - Assume we have an array which contains term frequency of each document. Where each row is a document, each column is a word, and the value denotes the frequency of the word in the document. Define a function named "analyze_tf" which:
      * takes the array as an input
      * normalizes the frequency of each word as: word frequency divided by the length of the document. Save the result as an array named **tf** (i.e. term frequency)
      * calculates the document frequency (**df**) of each word, e.g. how many documents contain a specific word
      * calculates **tf_idf** array as: **tf / df** (tf divided by df). The reason is, if a word appears in most documents, it does not have the discriminative power and often is called a "stop" word. The inverse of df can downgrade the weight of such words.
      * for each document, find out the **indexes of words with top 3 largest values in the tf_idf array**. Print out these indexes.
      * returns the tf_idf array.
 - Note, for all the steps, ** do not use any loop**. Just use array functions and broadcasting for high performance computation.

## 2. Define a function to analyze car dataset using pandas
 - Define a function named "analyze_cars" to do the follows:
   * Read "cars.csv" as a dataframe with the first row in the csv file as column names
   * Sort the data by "cylinders" and "mpg" in decending order and report the first three rows after sorting
   * Create a new column called "brand" to store the brand name as the first word in "car" column (hint: use "apply" function)
   * Show the mean, min, and max acceleration values by "cylinders" for each of these brands: "ford", "buick" and "honda"
   * Create a cross tab to show the average mpg of each brand and each clinder value. Use "brand" as row index and "cylinders" as column index. 
 - This function does not have any return. Just print out the result of each calculation step.

## Submission Guideline##
- Following the solution template provided below. Use __main__ block to test your functions
- Save your code into a python file (e.g. assign1.py) that can be run in a python 3 environment. In Jupyter Notebook, you can export notebook as .py file in menu "File->Download as".
- Make sure you have all import statements. To test your code, open a command window in your current python working folder, type "python assign1.py" to see if it can run successfully.

In [12]:
# Structure of your solution to Assignment 1
import numpy as np
import pandas as pd

def analyze_tf(arr):
    
    A = np.sum(arr, axis=1)
    
    #print(arr)
    #print(A)
    tf = arr.T / A
    #print(tf.T)
    x=np.where(tf.T>0,1,0)
    #print(x)
    df = np.sum(x, axis=0)
    #print(df)
    D = tf.T / df
    #print(D)
    tf_idf=np.argsort(D)
    #print(tf_idf)
    #print(tf_idf[:,::-1][:,0:3])
    
    return tf_idf[:,::-1][:,0:3]

def analyze_cars():
    
    # add your code
    data=pd.read_csv('cars.csv', header=0)
    print(data)
    sort = data.sort_values(by=['cylinders','mpg'], ascending=False)
    print(sort.head(3))
    sort['brand'] = sort.apply(lambda row: \
        row["car"].split()[0], axis=1)
    print(sort)
    tmp = sort[(sort.brand=='ford') | (sort.brand=='buick') | (sort.brand=='honda')]
    #print(tmp)
    grouped=tmp.groupby('cylinders')
    print(grouped.mean())
    print(grouped.min())
    print(grouped.max())
    print(pd.crosstab(index=sort.brand, columns=sort.cylinders, values=sort.mpg, aggfunc=np.average ))
    

# best practice to test your class
# if your script is exported as a module,
# the following part is ignored
# this is equivalent to main() in Java

if __name__ == "__main__":  
    
    #1 Test Question 1
    arr=np.random.randint(0,3,(4,8))
    #print(arr)
    tf_idf=analyze_tf(arr)
    print(tf_idf)
    
    # Test Question 2
    analyze_cars()

[[5 7 1]
 [7 4 1]
 [2 1 0]
 [2 0 3]]
      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
5    15.0          8           429        198    4341          10.0     70   
6    14.0          8           454        220    4354           9.0     70   
7    14.0          8           440        215    4312           8.5     70   
8    14.0          8           455        225    4425          10.0     70   
9    15.0          8           390        190    3850           8.5     70   
10   15.0          8           383        170    3563          10.0     70   
11   14.0          8       